#!/bin/sh

echo "// This file is generated by script, but also commited in git"
echo "// because it's a bootstrap requirement."

for fn in "$@"; do
    base=$(basename $fn .fth)
    echo "unsigned char ${base}_bin[] = { "
    ./zasm.sh $fn | xxd -i -
    echo " };"
done

