// This file is generated by script, but also commited in git
// because it's a bootstrap requirement.
unsigned char plus_bin[] = { 
  0xe1, 0xd1, 0x19, 0xe5
 };
unsigned char swap_bin[] = { 
  0xe1, 0xd1, 0xe5, 0xd5
 };
